### PR TITLE
Turn all Colors into StrEnum,

### PR DESCRIPTION
**Pull request by Carreau**
This make a few things a bit easier, like looping through variants, and also should be a bit stricter on types.

### CODE REVIEW

**Comment by Carreau** [comment]
Hum, StrEnum is only 3.11+. I'm not sure what to do. I guess we can still make it "just" an enum on earlier Versions.

**Comment by trallard** [comment]
I only saw this @Carreau could we not use `future` like `from __future__ import StrEnum` to go around this?

**Comment by Carreau** [comment]
We could use https://pypi.org/project/StrEnum/, but I don't think it's worth adding a dep just for this.

**Comment by trallard** [comment]
Yeah so maybe a simple enum would be good then

**Pull request closed without merging**
